export default [
  {
    files: ["src/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        window: "readonly",
        document: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        fetch: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        AbortController: "readonly",
        TextDecoder: "readonly",
        URL: "readonly",
        Blob: "readonly",
        console: "readonly",
        alert: "readonly",
        navigator: "readonly",
        Event: "readonly",
        DefaultPresets: "readonly",
        Page: "readonly",
        Native: "readonly",
        C: "readonly",
        Defaults: "readonly",
        State: "readonly",
        Util: "readonly",
        Runtime: "readonly",
        ErrorKit: "readonly",
        Store: "readonly",
        Acode: "readonly",
        Editor: "readonly",
        Patch: "readonly",
        Prompt: "readonly",
        Client: "readonly",
        AgentTools: "writable",
        PermissionModel: "readonly",
        Templates: "readonly",
        UI: "readonly",
        ace: "readonly",
        acode: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
      "no-unused-vars": "off",
      "no-empty": ["warn", { allowEmptyCatch: true }],
    },
  },
  {
    files: ["tools/**/*.mjs"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: { console: "readonly", process: "readonly" },
    },
    rules: { "no-undef": "error" },
  },
];
